name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        #Fix: Install pip, pipenv before using it
      - name: Install Python, pip, and pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Verify Pipenv Installation
        run: pipenv --version 

        #Fix: Ensure Pipfile.lock exists before using pipenv
      - name: Generate Pipfile.lock if missing
        run: |
          if [ ! -f Pipfile.lock ]; then
            pipenv lock
          fi
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
